Tugas2PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile.urls as profile
import dashboard.urls as dashboard
import forum.urls as forum


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=True), name='index'),
]

forum/urls.py
from django.conf.urls import url
from .views import index, tambah_forum, tambah_komentar, logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tambah-forum/$', tambah_forum, name='tambah-forum'),
    url(r'^tambah-komentar/$', tambah_komentar, name='tambah-komentar'),
    url(r'^logout/$', logout, name='logout')
]

profile/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^createModel/$', createModel, name='createModel'),
]

profile/models.py
from django.db import models

class Company(models.Model):
    company_name = models.CharField(max_length=50)
    specialty = models.CharField(max_length=250)
    yearFounded = models.CharField(max_length=5)
    description = models.TextField(max_length=300)
    website = models.TextField(max_length=300)
    company_type = models.TextField(max_length=300)
    url_foto = models.CharField(max_length=300, default='DEFAULT VALUE')

profile/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from .models import Company
from django.core import serializers
import json

# Create your views here.
def index(request):
    # Company.objects.all().delete()
    html ='profile/profile.html'
    return render(request, html)

@csrf_exempt
def createModel(request):
    # Company.objects.all().delete()

    if request.method == 'POST':

        try:
            company = Company.objects.get(company_name=request.POST['name'])
        except:
            company_name = request.POST['name']
            specialty = request.POST['specialty']
            yearFounded = request.POST['year']
            description = request.POST['description']
            website = request.POST['website']
            company_type = request.POST['type']
            url = request.POST['url']
            company = Company(company_name=company_name, specialty=specialty, yearFounded=yearFounded,description=description,website=website,company_type=company_type, url_foto=url)
            company.save()

        data = model_to_dict(company)

        request.session['login'] = request.POST['name']

        print(data)

        return HttpResponse(data)

    else:
        return HttpResponseRedirect(reverse('dashboard:index'))

def model_to_dict(obj):
    data = serializers.serialize('json', [obj, ])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

profile/templates/profile/layout/base.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <script type="text/javascript" src="https://platform.linkedin.com/in.js">
      api_key: 816z2l1p1v9gwv
      authorize: true
      onLoad: onLinkedInLoad
      scope: r_basicprofile r_emailaddress rw_company_admin
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript">
      // Setup an event listener to make an API call once auth is complete
      function onLinkedInLoad() {
          IN.Event.on(IN, "auth", getProfileData);
          // IN.Event.on(IN, "auth", getUserData);
      }

      // Use the API call wrapper to request the member's profile data

      function getProfileData() {

        IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", "email-address","positions").result(function(data){
            var companyId = data.values[0].positions.values[0].company.id
            console.log("companynya " + companyId)
            IN.API.Raw("/companies/" + companyId + ":(id,name,ticker,description,company-type,founded-year,locations:(address),website-url,square-logo-url,specialties)?format=json").method("GET").result(displayProfileData).error(onError);
        });


      }

      function getCompanyId(data){
        companyId = data.values[0].positions.values[0].company.id
        console.log("idnya "+companyId)
      }




      // Handle the successful return from the API call
      function displayProfileData(data){
        $.ajax({
        async : false,
        method: 'POST',
        url: '{% url "profile:createModel" %}',
        data: {
          name: data.name,
          specialty: data.specialties.values[0],
          year:data.foundedYear,
          description:data.description,
          website:data.websiteUrl,
          type:data.companyType.name,
          url:data.squareLogoUrl

        },
        dataType: 'json',
        success: function(company) {
          window.data = data;
          console.log(data);

            $("#judul").html(company.company_name);
            $("#CompanyName").html(company.company_name);
            $("#website").html(company.website);
            $("#description").html(company.description);
            $("#founded").html("Founded: " +company.yearFounded);
            $("#specialty").html("Specialty: " +company.specialty)
            $("#type").html(company.type);
            $("#address").html(data.locations.values[0].address.city
            + " " +data.locations.values[0].address.postalCode+ " "+ data.locations.values[0].address.street1);
            $("#logo").html('<img src="'+data.squareLogoUrl+'" />')

            document.getElementById('profileData').style.display = 'block';
            document.getElementById('header').style.display = 'block';
            document.getElementById('footer').style.display = 'block';

        },
        error: function(error) {
          alert("yah error");
          console.log(error);
        }
        });


      }

      // Handle an error response from the API call
      function onError(error) {
          console.log(error);
      }

      // Destroy the session of linkedin
      function logout(){
          IN.User.logout(removeProfileData);
      }

      // Remove profile data from page
      function removeProfileData(){
          document.getElementById('profileData').remove();
          document.getElementById('header').remove();
          document.getElementById('footer').remove();
      }
  </script>
  <script src="{% static 'js/profile.js' %}"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />


	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,400,400i,500,500i,600,600i,700,700i,800" rel="stylesheet">

<title>
    {% block title %} BukaHati | Profile {% endblock %}
  </title>
</head>

<body>
  <header id="header" style="display: none;">
    {% include "profile/partials/header.html" %}
  </header>
    <!-- content -->
  <content>
    {% block content %}
    <!-- content goes here -->
    {% endblock %}
  </content>
  <footer id='footer' style="display: none;">
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %} {% include "profile/partials/footer.html" %} {% endblock %}
  </footer>
  <!-- Jquery n Bootstrap Script -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% block javascript %} {% endblock %}
</body>
</html>