Tugas2PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile.urls as profile
import dashboard.urls as dashboard
import forum.urls as forum


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=True), name='index'),
]

forum/urls.py
from django.conf.urls import url
from .views import index, tambah_forum, tambah_komentar, logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tambah-forum/$', tambah_forum, name='tambah-forum'),
    url(r'^tambah-komentar/$', tambah_komentar, name='tambah-komentar'),
    url(r'^logout/$', logout, name='logout')
]

forum/models.py
from django.db import models

from profile.models import Company

class Forum(models.Model):
    pengguna = models.ForeignKey(Company)
    isi = models.CharField('isi', max_length=400, default='DEFAULT VALUE')
    nomor = models.IntegerField(blank=True, null=True)

class Komentar(models.Model):
    forum = models.ForeignKey(Forum, null=True)
    nama = models.CharField('nama', max_length=400, default='DEFAULT VALUE')
    isi = models.CharField('isi', max_length=400, default='DEFAULT VALUE')

forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Forum, Komentar
from profile.models import Company

# Create your views here.
def index(request):
    if not 'login' in request.session:
        return HttpResponseRedirect(reverse('dashboard:index'))
    else:
        nama = request.session['login']

        pengguna = Company.objects.get(company_name = nama)

        gambar = pengguna.url_foto

        forum = Forum.objects.filter(pengguna = pengguna)

        komentar = kumpulkan_komentar(forum)

        page = request.GET.get('page', 1)
        paginator = Paginator(forum, 3)

        navigasi = paginator.page(page)

        response = {'nama' : nama, 'forum' : forum, 'komentar' : komentar, 'gambar' : gambar, 'navigasi' : navigasi}

        return render(request, 'forum/forum.html', response)

def kumpulkan_komentar(forum):
    komentar = []

    for i in forum:
        a = Komentar.objects.filter(forum = i)
        for j in a:
            komentar.append(j)

    return komentar

@csrf_exempt
def tambah_forum(request):
    if request.method == 'POST':
        nama = request.POST['nama']
        isi = request.POST['isi']
        nomor = request.POST['nomor']

        pengguna = Company.objects.get(company_name = nama)

        forum = Forum()
        forum.pengguna = pengguna
        forum.isi = isi
        forum.nomor = nomor
        forum.save()

        return HttpResponse(status=200)

    else:
        return HttpResponse(status=403)

@csrf_exempt
def tambah_komentar(request):
    if request.method == 'POST':
        isi = request.POST['isi']
        nomor = request.POST['nomor']

        forum = Forum.objects.get(nomor = nomor)

        komentar = Komentar()
        komentar.forum = forum
        komentar.isi = isi
        komentar.nama = request.session['login']
        komentar.save()

        ambil = Komentar.objects.filter(isi = isi)

        return HttpResponse(status=200)

    else:
        return HttpResponse(status=403)

def logout(request):
    request.session.flush() # menghapus semua session

    return HttpResponseRedirect(reverse('dashboard:index'))

forum/templates/forum/forum.html
{% extends "forum/layout/base.html" %}

{% block content %}
<!-- Content Here -->
<div class='col-md-9' >
    <section id="data-dashboard">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class='panel-title'> Forum </h2>
            </div>

            <div class="panel-body">
                {% if forum %}
                    {% for i in navigasi %}
                    {% with forloop.counter as counter1 %}
                        <div class='row'>
                            <div class='col-md-1'>
                                 {{ i.nomor }} .
                            </div>
                            <img src="{{ gambar }}" style='height:100px' class='col-md-2 img-responsive '/>
                            <div class='col-md-9'>
                                <div class='row'>
                                    <div class='col-md-9'>
                                        <h3  style='margin-top:0px'>{{ nama }}</h3>
                                        <p id='{{ counter1 }}'>{{ i.isi }}</p>
                                    </div>
                                    <button class='btn btn-default col-md-2' id='tombolBalas{{ forloop.counter }}' onclick="tambahKomentar( {{ i.nomor }} )">Balas</button>
                                    <button class='btn btn-danger col-md-2' id='tombolBatal{{ forloop.counter }}' style='display:none' onclick="batalKomentar( {{ forloop.counter }} )">Batal</button>
                                </div>
                            </div>
                        </div>
                        <hr/>

                        {% if komentar %}
                            {% for j in komentar %}
                                {% if j.forum.nomor == i.nomor %}
                                    <div class='row'>
                                        <div class='col-md-2'>

                                        </div>
                                        <img src="{{ gambar }}" style='height:100px' class='col-md-2 img-responsive '/>
                                        <div class='col-md-8'>
                                            <div class='row'>
                                                <div class='col-md-9'>
                                                    <h3  style='margin-top:0px'>{{ j.nama }}</h3>
                                                    <p id='{{ forloop.counter }}'>{{ j.isi }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr/>
                                {% endif %}
                            {% endfor %}
                        {% endif %}

                        <div class='row'>
                            <div class='col-md-3'></div>
                            <div class='col-md-7'  id='komentar{{ i.nomor }}'></div>
                        </div>

                    {% endwith %}
                    {% endfor %}
                {% else %}
                    <div class="alert alert-danger text-center">
                        <strong>Opps!</strong> Tidak ada Forum
                    </div>
                {% endif %}
            </div>

        </div>

    </section>
</div>

<div class='col-md-3'>
    <form>
        <div class="form-group">
          <textarea class="form-control" rows="5" id="comment"></textarea>
        </div>
    </form>
    <a href="" class="btn btn-info" onclick="tambahForum( {{ forum|length }} )">Tambah Forum</a>
</div>

<div class='row'>
    {% if navigasi.has_other_pages %}
      <ul class="pagination">
        {% if navigasi.has_previous %}
          <li><a href="?page={{ navigasi.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in navigasi.paginator.page_range %}
          {% if navigasi.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if navigasi.has_next %}
          <li><a href="?page={{ navigasi.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
</div>

{% endblock %}

{% block javascript %}
<script>
    tambahForum = function(jumlah) {
        $.ajax({
            async : false,
            method : 'POST',
            url : '{% url "forum:tambah-forum" %}',
            data : {
                'nama' : '{{ nama }}',
                'isi' : $('textarea').val(),
                'nomor' : jumlah + 1,
            },
        })
    };

    var tambahKomentar = function (angka) {
        var html =
        '<form>' +
            '<div class="form-group">' +
              '<textarea class="form-control" rows="5" id="tulisKomentar"></textarea>' +
            '</div>' +
            '<div class="pull-right">' +
                '<a href="" class="btn btn-info" onclick=\"postKomentar(' + angka + ')\">Kirim</a>' +
            '</div>' ;

        '</form>' ;

        $('#komentar' + angka).append(html);

        $('#tombolBalas' + angka).hide();
        $('#tombolBatal' + angka).show();

    };

    var batalKomentar = function (angka) {
        $('#komentar' + angka).html("");
        $('#tombolBalas' + angka).show();
        $('#tombolBatal' + angka).hide();
    }

    var postKomentar = function (angka) {
        // alert($('#' + angka).text());
            // alert(angka);
        $.ajax({
            async : false,
            method : 'POST',
            url : '{% url "forum:tambah-komentar" %}',
            data : {
                'isi' : $('#tulisKomentar').val(),
                'nomor' : angka
            },
        })
    }

</script>

{% endblock %}