Tugas2PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile.urls as profile
import dashboard.urls as dashboard
import forum.urls as forum


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=True), name='index'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_comment/$', add_comment, name='add_comment'),
]

forum/urls.py
from django.conf.urls import url
from .views import index, tambah_forum, tambah_komentar, logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tambah-forum/$', tambah_forum, name='tambah-forum'),
    url(r'^tambah-komentar/$', tambah_komentar, name='tambah-komentar'),
    url(r'^logout/$', logout, name='logout')
]

react/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_comment/$', add_comment, name='add_comment'),
]

dashboard/models.py
from django.db import models

# Create your models here.

react/models.py
from django.db import models

dashboard/views.py
from django.shortcuts import render
from forum.models import Forum,Komentar
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

response = {}
def index(request):
	forum1 = Forum.objects.all()
	komentar = kumpulkan_komentar(forum1)
	html = 'dashboard/react.html'
	response['gambar'] = "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0NzU2OTYyN15BMl5BanBnXkFtZTgwMTkwOTg2MTI@._V1_SX300.jpg"
	response['forum'] = forum1
	response['komentar'] = komentar
	page = request.GET.get('page', 1)
	paginator = Paginator(forum1, 3)
	navigasi = paginator.page(page)
	response['navigasi'] = navigasi
	return render(request,html,response)

def kumpulkan_komentar(forum):
    komentar = []

    for i in forum:
        a = Komentar.objects.filter(forum = i)
        for j in a:
            komentar.append(j)

    return komentar

@csrf_exempt
def add_comment(request):
    if request.method == 'POST':
        isi = request.POST['isi']
        nomor = request.POST['nomor']

        forum = Forum.objects.get(nomor = nomor)

        komentar = Komentar()
        komentar.forum = forum
        komentar.isi = isi
        komentar.nama = request.POST['nama']
        komentar.save()

        ambil = Komentar.objects.filter(isi = isi)

        return HttpResponse(status=200)

    else:
        return HttpResponse(status=403)

react/views.py
from django.shortcuts import render
from forum.models import Forum,Komentar
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

response = {}
def index(request):
	forum1 = Forum.objects.all()
	komentar = kumpulkan_komentar(forum1)
	html = 'react.html'
	response['gambar'] = 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAjnAAAAJDBhNjYwZGU3LWZkYjMtNDA0NC1iNGQzLWU1YzA4MjE0ZGE2MQ.jpg'
	response['forum'] = forum1
	response['komentar'] = komentar
	page = request.GET.get('page', 1)
	paginator = Paginator(forum1, 3)
	navigasi = paginator.page(page)
	response['navigasi'] = navigasi
	return render(request,html,response)

def kumpulkan_komentar(forum):
    komentar = []

    for i in forum:
        a = Komentar.objects.filter(forum = i)
        for j in a:
            komentar.append(j)

    return komentar

@csrf_exempt
def add_comment(request):
    if request.method == 'POST':
        isi = request.POST['isi']
        nomor = request.POST['nomor']

        forum = Forum.objects.get(nomor = nomor)

        komentar = Komentar()
        komentar.forum = forum
        komentar.isi = isi
        komentar.nama = request.POST['nama']
        komentar.save()

        ambil = Komentar.objects.filter(isi = isi)

        return HttpResponse(status=200)

    else:
        return HttpResponse(status=403)

dashboard/templates/dashboard/react.html
{% extends "dashboard/layout/index.html" %}

{% block content %}
<!-- Content Here -->
<div class='col-md-9' >
    <section id="data-dashboard">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class='panel-title'> Forum </h2>
            </div>

            <div class="panel-body">
                {% if forum %}
                    {% for i in forum %}
                    {% with forloop.counter as counter1 %}
                        <div class='row'>
                            <div class='col-md-1'>
                                 {{ i.nomor }} .
                            </div>
                            <img src="{{ gambar }}" style='height:100px' class='col-md-2 img-responsive '/>
                            <div class='col-md-9'>
                                <div class='row'>
                                    <div class='col-md-9'>
                                        <h3  style='margin-top:0px'>{{ i.pengguna.company_name }}</h3>
                                        <p id='{{ counter1 }}'>{{ i.isi }}</p>
                                    </div>
                                    <button class='btn btn-default col-md-2' id='tombolBalas{{ forloop.counter }}' onclick="tambahKomentar( {{ i.nomor }} )">Balas</button>
                                    <button class='btn btn-danger col-md-2' id='tombolBatal{{ forloop.counter }}' style='display:none' onclick="batalKomentar( {{ forloop.counter }} )">Batal</button>
                                </div>
                            </div>
                        </div>
                        <hr/>

                        {% if komentar %}
                            {% for j in komentar %}
                                {% if j.forum.nomor == i.nomor %}
                                    <div class='row'>
                                        <div class='col-md-2'>

                                        </div>
                                        <img src="{{ gambar }}" style='height:100px' class='col-md-2 img-responsive '/>
                                        <div class='col-md-8'>
                                            <div class='row'>
                                                <div class='col-md-9'>
                                                    <h3  style='margin-top:0px'>{{ j.nama }}</h3>
                                                    <p id='{{ forloop.counter }}'>{{ j.isi }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr/>
                                {% endif %}
                            {% endfor %}
                        {% endif %}

                        <div class='row'>
                            <div class='col-md-3'></div>
                            <div class='col-md-7'  id='komentar{{ i.nomor }}'></div>
                        </div>

                    {% endwith %}
                    {% endfor %}
                {% else %}
                    <div class="alert alert-danger text-center">
                        <strong>Opps!</strong> Tidak ada Forum
                    </div>
                {% endif %}
            </div>

        </div>

    </section>
</div>

{% endblock %}

{% block javascript %}
<script>
    var tambahKomentar = function (angka) {
        var html =
        '<form>' +
        'Tulis Nama'+
        '<input class="form-control" id="tulisNama">' +
            '<div class="form-group">' +

            '<br>Tulis Komentar'+
              '<textarea class="form-control" rows="5" id="tulisKomentar"></textarea>' +
            '</div>' +

            '<div class="pull-right">' +
                '<a href="" class="btn btn-info" onclick=\"postKomentar(' + angka + ')\">Kirim</a>' +
            '</div>' +

        '</form>' ;

        $('#komentar' + angka).append(html);

        $('#tombolBalas' + angka).hide();
        $('#tombolBatal' + angka).show();

    };

    var batalKomentar = function (angka) {
        $('#komentar' + angka).html("");
        $('#tombolBalas' + angka).show();
        $('#tombolBatal' + angka).hide();
    }

    var postKomentar = function (angka) {
        // alert($('#' + angka).text());
            // alert(angka);
        $.ajax({
            async : false,
            method : 'POST',
            url : '{% url "dashboard:add_comment" %}',
            data : {
            	'nama' : $('#tulisNama').val(),
                'isi' : $('#tulisKomentar').val(),
                'nomor' : angka
            },
        })
    }
</script>

{% endblock %}