Tugas2PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile.urls as profile
import dashboard.urls as dashboard
import forum.urls as forum


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=True), name='index'),
]

forum/urls.py
from django.conf.urls import url
from .views import index, tambah_forum, tambah_komentar, logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tambah-forum/$', tambah_forum, name='tambah-forum'),
    url(r'^tambah-komentar/$', tambah_komentar, name='tambah-komentar'),
    url(r'^logout/$', logout, name='logout')
]

forum/models.py
from django.db import models

from profile.models import Company

class Forum(models.Model):
    pengguna = models.ForeignKey(Company)
    isi = models.CharField('isi', max_length=400, default='DEFAULT VALUE')
    nomor = models.IntegerField(blank=True, null=True)

class Komentar(models.Model):
    forum = models.ForeignKey(Forum, null=True)
    nama = models.CharField('nama', max_length=400, default='DEFAULT VALUE')
    isi = models.CharField('isi', max_length=400, default='DEFAULT VALUE')

forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Forum, Komentar
from profile.models import Company

# Create your views here.
def index(request):
    if not 'login' in request.session:
        return HttpResponseRedirect(reverse('dashboard:index'))
    else:
        nama = request.session['login']

        pengguna = Company.objects.get(company_name = nama)

        gambar = pengguna.url_foto

        forum = Forum.objects.filter(pengguna = pengguna)

        komentar = kumpulkan_komentar(forum)

        page = request.GET.get('page', 1)
        paginator = Paginator(forum, 3)

        navigasi = paginator.page(page)

        response = {'nama' : nama, 'forum' : forum, 'komentar' : komentar, 'gambar' : gambar, 'navigasi' : navigasi}

        return render(request, 'forum/forum.html', response)

def kumpulkan_komentar(forum):
    komentar = []

    for i in forum:
        a = Komentar.objects.filter(forum = i)
        for j in a:
            komentar.append(j)

    return komentar

@csrf_exempt
def tambah_forum(request):
    if request.method == 'POST':
        nama = request.POST['nama']
        isi = request.POST['isi']
        nomor = request.POST['nomor']

        pengguna = Company.objects.get(company_name = nama)

        forum = Forum()
        forum.pengguna = pengguna
        forum.isi = isi
        forum.nomor = nomor
        forum.save()

        return HttpResponse(status=200)

    else:
        return HttpResponse(status=403)

@csrf_exempt
def tambah_komentar(request):
    if request.method == 'POST':
        isi = request.POST['isi']
        nomor = request.POST['nomor']

        forum = Forum.objects.get(nomor = nomor)

        komentar = Komentar()
        komentar.forum = forum
        komentar.isi = isi
        komentar.nama = request.session['login']
        komentar.save()

        ambil = Komentar.objects.filter(isi = isi)

        return HttpResponse(status=200)

    else:
        return HttpResponse(status=403)

def logout(request):
    request.session.flush() # menghapus semua session

    return HttpResponseRedirect(reverse('dashboard:index'))

forum/templates/forum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">

    <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">

    <title>
        Forum
    </title>
</head>
<body>
    <div id="qunit" hidden></div>
    <header>
        <div class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="icon-bar"></span>

                  </button>
                  <a class="navbar-brand" href="#">Forum</a>
              </div>
              <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav ">
                      <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
                  </ul>
                  <ul class="nav navbar-nav ">
                      <li><a href="{% url 'profile:index' %}">Profile</a></li>
                  </ul>

                  <ul class="nav navbar-nav navbar-right ">
                      <li><a href="{% url 'forum:logout' %}">LOGOUT</a></li>
                  </ul>

              </div>

          </div>
      </div>

    </header>

    <content>
        <div class='container'>
            <div class='row'>
                {% block content %}
                    <!-- content goes here -->
                {% endblock %}
            </div>
            <hr>
        </div>
    </content>

    <footer>
        <h2 class='panel-title' style="text-align:center">Forum</h2>
    </footer>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
    {% block javascript %}

    {% endblock %}


</body>
</html>